### PR TITLE
Epic 13 Task 3.1 Notification components 

### PR DESCRIPTION
**Pull request by ishat005**
## Description
In this pull request I have implemented the notifications components part when the user tries to signup, and signs in. Also I have implemented the notifications for homepage upon successful signup and login of user.

## Changes

- [ ] Modified actual snackbar
- [ ] Added the handleOpenSnackbar at appropriate places in Signup and Login file
- [ ] Created a new Snackbar component along with stylings for homepage and added logic for display of snackbar upon login and signup

## Screenshots
Screenshot 2024-08-16 112309
Screenshot 2024-08-16 113336
Screenshot 2024-08-16 113306
Screenshot 2024-08-16 112408
Screenshot 2024-08-16 112334

### CODE REVIEW

**Comment by YanbingChen** [comment]
I noticed that the recent changes to the SnackBar component override the severity styles, which could lead to all alerts looking the same as what you changed, regardless of their type. Since this component is used in many other pages, modifying the background and color in this way will cause inconsistencies and potentially break the design on those pages.

Maybe we could add a new prop, like loginNotificationStyle, that acts as a toggle between the original style and the custom style specifically for login notifications. This way, we can apply the custom styles where needed without affecting the default severity-based styles. 

Let me know what you think!

**Comment by ishat005** [comment]
> I noticed that the recent changes to the SnackBar component override the severity styles, which could lead to all alerts looking the same as what you changed, regardless of their type. Since this component is used in many other pages, modifying the background and color in this way will cause inconsistencies and potentially break the design on those pages.
> 
> Maybe we could add a new prop, like loginNotificationStyle, that acts as a toggle between the original style and the custom style specifically for login notifications. This way, we can apply the custom styles where needed without affecting the default severity-based styles.
> 
> Let me know what you think!

**Comment by ishat005** [comment]
Yup I think we can do the prop. But how can we implement the prop in this? I am not sure how we can proceed with having a login prop.

**Comment by YanbingChen** [comment]
> Yup I think we can do the prop. But how can we implement the prop in this? I am not sure how we can proceed with having a login prop.

Hi Isha,

I’ve added a new loginNotificationStyle prop to the SnackBar component, which allows your custom styles to be applied without affecting other pages. I’ve also updated handleOpenSnackBar to pass this prop where needed. All instances where you added handleOpenSnackBar now include the new prop set to true to activate your custom styles.

I didn’t run any tests since I'm not familiar with your testing process, so please verify that everything works as expected.

Additionally, since right now you’ve implemented only one new style using the SnackBar component, I’ve set the new prop as a boolean to toggle the style on or off. In the future, if you or others need to introduce more custom styles, it might be worth considering switching to a useCustomStyle prop that takes a string and defaults to null. That way, you could easily switch between multiple custom styles.

Let me know if you have any questions or need any further help!

**Comment by ishat005** [comment]
> > Yup I think we can do the prop. But how can we implement the prop in this? I am not sure how we can proceed with having a login prop.
> 
> Hi Isha,
> 
> I’ve added a new loginNotificationStyle prop to the SnackBar component, which allows your custom styles to be applied without affecting other pages. I’ve also updated handleOpenSnackBar to pass this prop where needed. All instances where you added handleOpenSnackBar now include the new prop set to true to activate your custom styles.
> 
> I didn’t run any tests since I'm not familiar with your testing process, so please verify that everything works as expected.
> 
> Additionally, since right now you’ve implemented only one new style using the SnackBar component, I’ve set the new prop as a boolean to toggle the style on or off. In the future, if you or others need to introduce more custom styles, it might be worth considering switching to a useCustomStyle prop that takes a string and defaults to null. That way, you could easily switch between multiple custom styles.
> 
> Let me know if you have any questions or need any further help!

The prop is working well 👍 thank you :-)

**Review by JornsenChao — APPROVED** [review]

**Pull request merged**
